AllCops:
  TargetRubyVersion: 2.6.0
  Exclude:
    - "bin/*"
    - "./**/*.gemspec"
    - "Gemfile"
    - "Rakefile"
    - "templates/*"
    - vendor/bundle/**/*

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "./**/spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - Gemfile

Layout/DotPosition:
  # Multi-line method chaining should be done with trailing dots.
  EnforcedStyle: trailing

Style/TrailingCommaInArguments:
  # If `comma`, the cop requires a comma after the last argument, but only for
  # parenthesized method calls where each argument is on its own line.
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  # If `comma`, the cop requires a comma after the last item in an array,
  # but only when each item is on its own line.
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  # If `comma`, the cop requires a comma after the last item in a hash,
  # but only when each item is on its own line.
  EnforcedStyleForMultiline: comma

Style/MutableConstant:
  # Do not assign mutable objects to constants.
  Enabled: false

Style/Documentation:
  # Document classes and non-namespace modules
  Enabled: false

Style/ClassAndModuleChildren:
  # Checks style of children classes and modules.
  Enabled: false

Style/FrozenStringLiteralComment:
  # Checks existence of the frozen string literal comment
  Enabled: true

Style/RescueStandardError:
  # Checks that you are including the error class
  # when you rescue
  Enabled: false

Style/PercentLiteralDelimiters:
  # Percent literal delimeters are always parentheses
  PreferredDelimiters:
    { default: (),
    '%i': '()',
    '%I': '()',
    '%r': '()',
    '%w': '()',
    '%W': '()'
    }
