#!/usr/bin/env ruby
# frozen_string_literal: true

require "pathname"

source_path = (Pathname.new(__FILE__).dirname + "../lib").expand_path
$LOAD_PATH << source_path

require "namecard"

if ["-v", "--version"].include? ARGV[0]
  puts New::VERSION
  exit 0
end

Namecard.log_to_console
