name: Publish

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: ruby
          package-name: andrewmcodes
          bump-minor-pre-major: true
          version-file: "lib/andrewmcodes/version.rb"
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: andrewmcodes/actions/setup-ruby@main
        if: ${{ steps.release.outputs.release_created }}
      - run: |
          gem install bundler -v 2.4
          bundle install
          bin/rspec
        if: ${{ steps.release.outputs.release_created }}
      - name: release gem
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{ secrets.GEM_HOST_API_KEY }}"
        if: ${{ steps.release.outputs.release_created }}
